package com.yayandroid.componentdispatcher.contract

interface ApplicationComponent

interface CoreApplicationComponent : ApplicationComponent

interface FeatureApplicationComponent : ApplicationComponent